---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: niri-desktop
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/blue-build/base-images/fedora-kinoite
image-version: latest # latest is also supported if you want new updates ASAP

stages:
  - name: niri-build
    from: registry.fedoraproject.org/fedora:43
    modules:
      - type: niri-build
        source: local
        repository: "https://github.com/niri-wm/niri.git"
        branch: "wip/branch"
        output_bin: "/out/niri"
        output_runtime: "/out/runtime"
  - name: pijul-build
    from: registry.fedoraproject.org/fedora:43
    modules:
      - type: pijul-build
        source: local
        repository: "https://nest.pijul.com/pijul/pijul"
        branch: "main"
        features: "git"
        output_bin: "/out/pijul"


# module configuration, executed in order
# you can include multiple instances of the same module
modules:

  - from-file: modules/build-copy.yml

  - from-file: modules/kernel.yml
  - from-file: modules/packages.yml
  - from-file: modules/base-files.yml
  - from-file: modules/polkit-agent.yml
  - from-file: modules/kde-cleanup.yml
  - from-file: modules/grub-theme-local.yml
  - from-file: modules/icons-whitesur.yml
  - from-file: modules/fcitx5-theme-ori.yml
  - from-file: modules/fonts.yml
  - from-file: modules/gschema-overrides.yml
  - from-file: modules/brew.yml
  - from-file: modules/chezmoi.yml
  - from-file: modules/flatpaks.yml
  - from-file: modules/flatpak-overrides.yml
  - from-file: modules/os-release.yml
  - from-file: modules/signing.yml
