#!/bin/sh
exec tail -n +3 $0
# This file provides an easy place for custom GRUB menu entries.
# Run grub2-mkconfig on the installed system after editing entries below.
#
# Example UEFI chainload entry:
# menuentry "Windows Boot Manager (UEFI)" {
#     insmod part_gpt
#     insmod fat
#     search --no-floppy --fs-uuid --set=root XXXX-XXXX
#     chainloader /EFI/Microsoft/Boot/bootmgfw.efi
# }
